# .streamlit/secrets.toml
github_token = "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"
repo_owner = "ajlewisl23"
repo_name = "Manual_storm_classification"
